[package]
name = "shift_carry_encryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
